<?php
$ltmp_preset['en']=[
	'js'=>[
		'errors'=>[
			'account_length_less'=>'Login is too short',
			'account_first_symbol'=>'Login must start with a Latin character',
			'account_last_symbol'=>'Login must end with a Latin character or number',
			'account_already_exist'=>'Login is already used, please try another one',
			'captcha_expire'=>'Please tick in the captcha again',
			'captcha_invalid'=>'Captcha refused, try again',
			'server_error'=>'Server problem, please try later',
			'attempts_limit'=>'You have made more than 5 attempts in 5 minutes, wait a little and try again',
			'invite_already_activated'=>'The code has already been redeemed',
			'invite_not_founded'=>'Code isn’t found',
			'invalid_invite'=>'Invalid invite',
		],
		'success'=>[
			'invite'=>'You have successfully activated the code, the funds should arrive within 1 minute',
		],
	],
	'meta'=>[
		'title'=>'Get started with VIZ!',
		'description'=>'Register and get an account to interact with the VIZ ecosystem.',
	],
	'maintenance'=>[
		'title'=>'Maintenance',
		'description'=>'Maintenance is underway. The service will be available later.',
	],
	'index'=>[
		'waiting_caption'=>'Waiting for you to tick the box&hellip;',
		'intro_title'=>'Your first VIZ account',
		'intro_text'=>'
					<p>To create an account, you need to read the explanations below and tick some boxes. It takes a few minutes, but will save you from many problems and questions.</p>
					<p>VIZ accounts are different from social media accounts, email accounts, websites, etc. Your account is your personal account in the VIZ blockchain, in which you store your social capital - the main value in the ecosystem.</p>
					<p>With your account, social capital and viz tokens, you will reward people and receive rewards from them, subscribe, vote, and do other interesting things online and in "real life".</p>
					<p>Please note the features of the VIZ accounts and confirm that you are familiar with them:</p>',
		'section_7'=>'<p>Initially, your account is completely anonymous. While helping you to create it, we don’t ask for any personal data: no name, no email, no phone. You just create an account clicking one button and start using it. In the future, for convenience it can be linked to a nickname, name, social network account, phone number, etc. using various apps in the ecosystem. Or you can not to link.</p>',
		'section_7_check_caption'=>'Fine!',

		'section_6'=>'<p>Despite the fact that when you create an account you receive keys from it (more about it is below), we don’t know them. Keys are generated directly in your browser and aren’t downloaded to our servers. Until you share your account keys with someone, no one in the whole world, except you, will know them. It’s very secure, but it also means that if you lose your keys, no one can “remind”, “restore” or recreate them. Be careful and prudent! Keep copies of your keys in several secure places!</p>',
		'section_6_check_caption'=>'Clear!',

		'section_5'=>'<p>Almost all actions of your VIZ account (awards, transfers, voting) will be visible to curious and technically competent people. The VIZ blockchain is open-ended, this is not a mistake, it is intended that way. Behave yourself even if you are anonymous. Sooner or later, someone will probably find out who owns your account and will see the entire history of your actions. Or, stay anonymous and try not to reveal your identity.</p>',
		'section_5_check_caption'=>'I will a good boy! (But it isn’t exactly).',

		'section_4'=>'<p>Your capital and liquid viz coins are stored electronically on the blockchain. No one except you (or the one who knows your keys) can do anything with them: not only transfer them somewhere, but also “freeze”, “block”, “lose”, “not delegate”, etc., as banks or law enforcement officers sometimes do. At the same time, if a bad person finds out your account key and steals your coins, no one will return them to you. Blockchain is not a bank, you have complete control over your assets and are fully responsible for them. There is no one to complain to. </p>',
		'section_4_check_caption'=>'Cruelly, but fair!',

		'section_3'=>'
				<p>About keys in brief. Key with user’s terms of reference is something like a password, but with restrictions on how to use it. When creating an account, you’ll receive four different keys (in general, there are more of them in VIZ, but the rest are needed only for very advanced users). The keys can’t be created on your own, they are generated by a special algorithm, look like very long lines of letters and numbers and start with 5.</p>
				<p>A <strong>regular key</strong> allows you to reward other users, write information to the blockchain, change account data and vote for apps in VIZ DAO Fund. This is the most harmless key, it’s impossible to do much damage with it. Therefore, it’s usually used in apps.</p>
				<p>The <strong>active key</strong> does everything that the regular one, but in addition, it allows you to manage your assets- viz coins in the wallet and social capital (as well as vote for delegates of the VIZ blockchain). If an attacker knew your active key, he can quickly and irrevocably steal coins from your wallet and enable the reduction of social capital. This key can only be used in a very small number of apps that you trust as much as possible.</p>
				<p>The owner key - the <strong>master key</strong>, allows you to do whatever you want with your account, as well as change other keys in case of their loss or compromise (or just for prevention). It’s better never use the master key and store it in multiple copies in very secure places. It’s needed only in extreme cases - when you need to change other keys after they have been compromised or when you give your account to another person.</p>
				<p>A <strong>memo key</strong> encrypts messages that can be added to awards, transfers, and some other transactions. Usually, notes are created and stored on the blockchain in the clear, but some apps make them incomprehensible to strangers. If someone finds out your note key, he can read all your secret messages.</p>',
		'section_3_check_caption'=>'Don’t worry about the regular key, look after the active ones, keep the master one in the safe!',

		'section_ask_invite'=>'Do you have an invite?',
		'section_ask_invite_yes'=>'Yes',
		'section_ask_invite_no'=>'No',

		'section_2_alt'=>'<p>The amount from your invite-cheque will be transferred to the capital of the new account. This will allow you to immediately get a full account. To increase capital, you can buy viz tokens or start receiving rewards from other members of the ecosystem.</p>',
		'section_2_alt_check_caption'=>'Capital - can’t do anything without it&hellip;',
		'section_1_alt'=>'<p>In the future, you will be able to register any number of new accounts and VIZ subaccounts at your own expense without invites and without the help of our registrar. To do this, you need to transfer 1 viz to the new account or delegate 10 viz.</p>',
		'section_1_alt_check_caption'=>'It will come in handy!',

		'alt_form_text'=>'<p>And now to the point!</p>',
		'alt_form_login'=>'<p>Enter the desired account name (small Latin letters and numbers, more than 2 characters, the first character must be a letter):</p>',
		'alt_form_login_placeholder'=>'— enter account name',
		'alt_form_invite'=>'<p>Enter the invite code:</p>',
		'alt_form_invite_placeholder'=>'— enter code',
		'alt_form_button'=>'Use code',

		'keys_title'=>'<h3>Congratulations!</h3>',
		'keys_account'=>'Your account: ',
		'keys_invite_balance'=>'Transferred to capital: ',
		'keys_text'=>'Your keys:',
		'keys_master'=>' &mdash; master key',
		'keys_active'=>' &mdash; active key',
		'keys_regular'=>' &mdash; regular key',
		'keys_memo'=>' &mdash; memo key',
		'keys_attention'=>'Save these keys in several places right now!',
		'keys_check_caption'=>'I confirm saving keys',

		'section_2'=>'
				<p>We will delegate the minimum social capital (1 viz) to your first account, which is enough for several actions. To become a full-fledged participant in the VIZ ecosystem, you need to accumulate at least a small amount of social capital or buy it (this is faster).</p>
				<!--<p>Ваш первый аккаунт будет абсолютно пустым, то есть без социального капитала. Это значит, что он не сможет выполнять никакие действия, кроме получения наград от других аккаунтов. Чтобы стать полноценным участником экосистемы ВИЗ, надо накопить хотя бы небольшой социальный капитал или купить его (это быстрее). Про оба способа мы расскажем после создания вашего аккаунта.</p>-->',
		'section_2_check_caption'=>'Capital - can’t do anything without it&hellip;',

		'section_1'=>'<p>Creating an account in a VIZ is on a paid basis. But VIZ.PLUS is ready to pay for your first account ("first dose is free"), as we want VIZ ecosystem to attract many people. Therefore, you will have to confirm that you are a human and not a mass registration bot. In the future, you can create any number of accounts at your own expense.</p>',

		'form_text'=>'
				<p>And now - to the point!</p>
				<p>You have 100 seconds to enter your account name. If you don’t have time, check the captcha box again.</p>',
		'form_login'=>'<p>Enter the desired account name (small Latin letters and numbers, more than 2 characters, the first character must be a letter):</p>',
		'form_login_placeholder'=>'— enter account name',
		'form_button'=>'Create',
	],
];

$ltmp_preset['en']=array_replace_recursive($ltmp_preset['ru'],$ltmp_preset['en']);